#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
  path: /
  controller: App\Controller\HomeController::indexAction

about:
  path: /about
  controller: App\Controller\AboutController::indexAction

cook:
  path: /cook/list
  controller: App\Controller\CookController::listAction

cook_show_products:
  path: cook/{id}/products
  controller: App\Controller\ProductController::showProductsAction

chef_new_product:
  path: /chef/{id}/new/products
  controller: App\Controller\Chef\ChefProductController::newAction

chef_list_products:
  path: /chef/{id}/list/products
  controller: App\Controller\Chef\ChefProductController::listAction

chef_edit_product:
  path: /chef/{id}/edit/products
  controller: App\Controller\Chef\ChefProductController::editAction

chef_delete_product:
  path: /chef/product/{id}/delete
  controller: App\Controller\Chef\ChefProductController::deleteAction

menu_list:
   path: /menu/list
   controller: App\Controller\MenuController::listAction

menu_show:
  path: /menu/show/{id}
  controller: App\Controller\MenuController::showAction

menu_create:
  path: /chef/{id}/new/menu
  controller: App\Controller\Chef\ChefMenuController::newAction
